### ISSUE TITLE
Root6 Compatibility

### ISSUE THREAD

**Issue by jgruszko** [rat-pac/rat-pac#69]
Are there any plans to make RAT compatible with root 6? It appears that root 5.34 cannot be built on MacOS Mojave (10.14.5), and there don't appear to be plans to add a patch to fix that, leaving Mac users unable to work with RAT's root libraries.

**Comment by nbarros** [comment]
The process is not hard (done in another "flavor" of RAT), but right now I have too many things on my plate. If nobody does this before, I will take care of it once I find some spare cycles. 

So, the answer to this issue is yes, there are plans to get it done. Unfortunately it may take me a couple of weeks to get it done, unless someone else does it in the meantime.

**Comment by nbarros** [comment]
@jgruszko Actually, as an update, I just installed ROOT 5 on my laptop (MacOS Mojave - 10.14.5), so I guess that, although desirable, it is not strictly necessary to use ROOT 6 on Mojave.

**Comment by jgruszko** [comment]
Interesting, I wasn’t able to install it, using the same OS. I kept encountering the error: 

Error: cannot open file "AvailabilityMacros.h"  /Users/jgruszko/Dev/root-5.34.38/build/include/RConfig.h:384:
Warning: Error occurred during reading source files
Warning: Error occurred during dictionary source generation
!!!Removing G__MetaUtils.cxx G__MetaUtils.h !!!
Error: ../../bin/rootcint_tmp: error loading headers...
make[2]: *** [core/metautils/G__MetaUtils.cxx] Error 1
make[1]: *** [core/metautils/CMakeFiles/METAUTILS_DICTIONARY.dir/all] Error 2
make: *** [all] Error 2

which seems to be related to Xcode’s command line tools. I tried uninstalling and reinstalling them, and kept encountering the same issue. Would you mind sending the configuration options you used (the output of “cmake -LA” would be ideal, I think)? 

Thanks, 
Julieta
-----------------------------------------
Julieta Gruszko
jgruszko@mit.edu <mailto:jgruszko@mit.edu>
Pappalardo Fellow
MIT Department of Physics
Building 26-559
(617) 253-2285
Pronouns: she/her/hers

**Comment by nbarros** [comment]
Aha...that is actually because Apple is silly and changed the SDK installation into a modular style causing ROOT to not find certain headers where they used to be by default. 

Please execute the following command from the terminal:

```bash
open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg
```

this will install the SDK headers in the place that ROOT expects it to be.

**Comment by jgruszko** [comment]
That did the trick, thank you! Given that we can keep working with root 5 for now, I'll close the issue.

**Comment by jrklein** [comment]
Julieta,
    Thanks for raising this.  As Nuno points out, we probably should do the upgrade at some point if we can find someone with the time to do it.  


     Josh
